app/models.py
from . import db
import datetime


class Pic_Table(db.Model):
    __tablename__ = 'pic_table'
    id = db.Column(db.Integer, primary_key=True)
    filename = db.Column(db.String(64), unique=True, nullable=False)  # 保存的文件名
    original_name = db.Column(db.String(64), nullable=True)  # 原始文件名
    filedate = db.Column(db.DateTime)  # 文件生成的时间
    detectdate = db.Column(db.DateTime, default=datetime.datetime.utcnow())  # 检测扇贝的时间
    picmd5 = db.Column(db.String(32))  # 计算图片的MD5值，记录下来。
    fanshells = db.relationship('Fanshell_data', backref='pic')

    def __repr__(self):
        return '<Filename: %r>' % self.filename


class Fanshell_data(db.Model):
    __tablename__ = 'fanshell_data'
    id = db.Column(db.Integer, primary_key=True)
    shell_no = db.Column(db.Integer)  # 一张纸上的扇贝编号
    shell_height = db.Column(db.Integer)  # 扇贝的高
    shell_width = db.Column(db.Integer)  # 扇贝的宽度
    shell_similar = db.Column(db.REAL)  # 扇贝的相似度
    shell_area = db.Column(db.Integer)  # 扇贝的面积
    # pic_filename = db.Column(db.String(64))  # 生成扇贝的图片名
    pic_id = db.Column(db.Integer, db.ForeignKey('pic_table.id'))

    def __repr__(self):
        return '<Shell No:%d Height:%d Width:%d>' % (self.shell_no, self.shell_height, self.shell_width)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import MultipleFileField, BooleanField, SubmitField
from flask_wtf.file import FileAllowed, FileRequired


class picForm(FlaskForm):
    pics = MultipleFileField('选择图片', validators=[FileRequired(), FileAllowed(['jpg', 'png'])])


class xlsForm(FlaskForm):
    checked = BooleanField('选择')
    makexls = SubmitField('生成并下载')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config
from flask_sqlalchemy import SQLAlchemy


# __author__ = '刘永海'
bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, template_folder="templates", static_folder='static')
from . import views, errors

app/main/views.py
from flask import render_template, request, redirect, url_for, current_app, send_from_directory, make_response
from . import main
from . import forms
import datetime
from .getshellsize import GetShellSize
import os
from werkzeug.utils import secure_filename
from ..models import Pic_Table, Fanshell_data, db
import hashlib
from .gen_xls import gen_xls


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in current_app.config['ALLOWED_EXTENSIONS']


def write_uploadedfile(filename):
    pass


@main.route('/', methods=['GET', 'POST'])
def index():
    form = forms.picForm()
    if request.method == 'POST':
        files = form.pics.data
        for file in files:
            if file and allowed_file(file.filename):
                origin_fname = secure_filename(file.filename)  # 记录原始文件名,安全的。
                ext = origin_fname.rsplit('.', 1)[1].lower()  # 获取文件名后缀
                newfname = datetime.datetime.now().strftime('%Y%m%d%H%M%S%f') + '.' + ext  # 新文件名
                file.save(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], newfname))
                pic = Pic_Table(filename=newfname, original_name=origin_fname)
                db.session.add(pic)  # 加照片信息
                db.session.commit()  # 提交数据
                mygss = GetShellSize(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], newfname))  # 照片识别类初始化，并加载照片
                ret, show, fans = mygss.auto_detect()
                if ret in (-1, 0, 1):
                    # -1 加载了照片但是未找到纸张0 找到纸张未检测到扇贝
                    mygss.save_pic(img=show, path=os.path.join(current_app.config['FINISHED_FOLDER'], newfname))
                    if ret == 1:
                        # 1 检测到了扇贝
                        for index, value in enumerate(fans):
                            fanshell = Fanshell_data(shell_no=index + 1, shell_height=value[0], shell_width=value[1], \
                                                     shell_similar=value[2], shell_area=value[3], pic=pic)
                            db.session.add(fanshell)
                        db.session.commit()
                else:
                    # -2 加载照片错误
                    pass
        return redirect(url_for('.index'))
    page = request.args.get('page', 1, type=int)
    pagination = Pic_Table.query.order_by(Pic_Table.detectdate.desc(), Pic_Table.id.desc()).paginate(page, per_page=current_app.config['PICS_PER_PAGE'], error_out=False)
    pics = pagination.items
    return render_template('newindex.html', form=form, pics=pics, pagination=pagination)


@main.route('/export_xls', methods=['GET', 'POST'])
def export_xls():
    form = forms.xlsForm()
    if request.method == 'POST':
        checked = request.form.getlist('checked')
        fans = []
        for sel in checked:
            pic = Pic_Table.query.filter(Pic_Table.id == sel).first()  # 取当前照片
            for p in pic.fanshells:
                fans.append(['{0:.1f}mm'.format(p.shell_height),
                             '{0:.1f}mm'.format(p.shell_width),
                             '{0:.1%}'.format(p.shell_similar),
                             '{0:.1f}c㎡'.format(p.shell_area),
                             pic.original_name])
        if len(fans) > 0:  # 有数据
            wb = gen_xls(['壳高', '壳长', '相似度', '扇贝面积', '文件名称'], fans)
            newfname = datetime.datetime.now().strftime('%Y%m%d%H%M%S%f') + '.xlsx'  # 新文件名
            wb.save(os.path.join(current_app.config['EXCEL_FOLDER'], newfname))
            response = make_response(send_from_directory(current_app.config['EXCEL_FOLDER'], newfname, as_attachment=True))
            response.headers['Content-Disposition'] = "attachment; filename={}".format(newfname.encode().decode('latin-1'))
            response.headers['Content-Type'] = 'application/octet-stream'
            return response
        return redirect(url_for('.export_xls'))
    page = request.args.get('page', 1, type=int)
    pagination = Pic_Table.query.filter(Pic_Table.fanshells.any()).order_by(Pic_Table.detectdate.desc(), Pic_Table.id.desc()).paginate(page, per_page=24, error_out=False)
    pics = pagination.items
    return render_template('export_xls.html', form=form, pagination=pagination, pics=pics)


@main.route('/finished/<filename>')
def getfinishedpic(filename):
    return send_from_directory(current_app.config['FINISHED_FOLDER'], filename)


@main.route('/uploads/<filename>')
def getuploadedpic(filename):
    return send_from_directory(current_app.config['UPLOADED_PHOTOS_DEST'], filename)

app/templates/basic_common/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
    <ul class="pagination">
        <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
            <a href="{% if pagination.has_prev %}{{ url_for(endpoint,
                    page = pagination.page - 1, **kwargs)}}{% else %}#{% endif %}">&laquo;</a>
        </li>
        {% for p in pagination.iter_pages() %}
            {% if p %}
                {% if p == pagination.page %}
                    <li class="active">
                {% else %}
                    <li>
                {% endif %}
                 <a href="{{ url_for(endpoint, page=p, **kwargs) }}">{{ p }}</a>
                    </li>
            {% else %}
                <li class="disabled"><a href="#">&hellip;</a></li>
            {% endif %}
        {% endfor %}
        <li{% if not pagination.has_next %} class="disabled"{% endif %}>
            <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.page + 1, **kwargs) }}{% else %}#{% endif %}">&raquo;</a>
        </li>
    </ul>
{% endmacro %}
{% macro make_pics(pic) %}
    <div class="col-md-3">
        <h7>照片名：{{ pic.original_name | truncate(25, True) }}</h7>
        <a href="{{ url_for('main.getfinishedpic', filename=pic.filename) }}">
            <img class="img-responsive" src="{{ url_for('main.getfinishedpic', filename=pic.filename) }}" alt="">
        </a>

        <table class="table table-bordered">
            <thead>
            <tr><th style="width: 50px">No.</th><th style="width: 80px">高</th><th style="width: 80px">长</th><th style="width: 80px">相似</th><th style="width: 80px">面积</th></tr>
            {% for fan in pic.fanshells %}
                <tr>
                    <td>{{ fan.shell_no|round(1) }}</td><td>{{ fan.shell_height|round(1) }}</td><td>{{ fan.shell_width|round(1) }}</td><td>{{ '%.1f%%' % (fan.shell_similar * 100) }}</td><td>{{ fan.shell_area|round(1) }}</td>
                </tr>
            {% endfor %}
            </thead>
        </table>
    </div>
{% endmacro %}

{% macro make_pics2(pic, checkbox) %}
    <div class="col-md-3">
        <img class="img-responsive" src="{{ url_for('main.getfinishedpic', filename=pic.filename) }}" alt="">
        {{ checkbox }}
{#        <input id="{{ pic.id }}" name="{{ pic.id }}" type="checkbox" value="n">#}
        此图识别扇贝 {{ pic.fanshells|count }} 只
    </div>
{% endmacro %}

app/templates/basic_common/base.html
<!DOCTYPE html>
<html lang="zh">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="{{ url_for('static', filename='favicon.ico')}}">

        <title>{% block title %}{% endblock %}</title>
        {% block css %}
            <!-- 新 Bootstrap 核心 CSS 文件 -->
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

            <!-- 可选的Bootstrap主题文件（一般不用引入） -->
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}">

            <!-- 个性化主题文件 -->
            <!-- font-awesome样式主题文体 -->
            <link href="{{ url_for('static',filename='css/font-awesome.css') }}" media="all" rel="stylesheet" type="text/css" />
            <!-- fileinput样式主题文体 -->
            <link href="{{ url_for('static',filename='css/fileinput.min.css') }}" media="all" rel="stylesheet" type="text/css" />
        {% endblock %}

        {% block js %}
            <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
            <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>

            <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
            <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

            <!-- 个性化 js 文件 -->
            <!-- piexif.min.js is only needed if you wish to resize images before upload to restore exif data.
             This must be loaded before fileinput.min.js -->
            <script src="{{ url_for('static',filename='js/plugins/piexif.min.js') }}" type="text/javascript"></script>
            <!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview.
                 This must be loaded before fileinput.min.js -->
            <script src="{{ url_for('static',filename='js/plugins/sortable.min.js') }}" type="text/javascript"></script>
            <!-- purify.min.js is only needed if you wish to purify HTML content in your preview for HTML files.
                 This must be loaded before fileinput.min.js -->
            <script src="{{ url_for('static',filename='js/plugins/purify.js') }}" type="text/javascript"></script>
            <!-- the main fileinput plugin file -->
            <script src="{{ url_for('static',filename='js/fileinput.min.js') }}"></script>
            <!-- optionally if you need a theme like font awesome theme you can include
                it as mentioned below -->
            <script src="{{ url_for('static',filename='js/themes/fa/theme.min.js') }}"></script>
            <!-- optionally if you need translation for your language then include
                locale file as mentioned below -->
            <script src="{{ url_for('static',filename='js/locales/zh.js') }}"></script>

        {% endblock %}
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-offset-2">
                    <div class="col-xs-12 col-sm-8">
                        {% block content %}

                        {% endblock %}
                    </div>
                </div>
            </div><!--/row-->
        </div><!--/.container-->
    </body>
</html>

app/templates/basic_common/mybase.html
{% extends 'bootstrap/base.html' %}
{% block title %}扇贝尺寸测算{% endblock title%}
{% block styles %}
    {{ super() }}
    <!-- fileinput样式主题文体 -->
    <link href="{{ url_for('static',filename='css/fileinput.min.css') }}" media="all" rel="stylesheet" type="text/css" />
{% endblock styles %}
{% block head %}
    {{ super() }}
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico')}}">
{% endblock head %}
{% block scripts %}
    {{ super() }}
    <!-- piexif.min.js is only needed if you wish to resize images before upload to restore exif data.
        This must be loaded before fileinput.min.js -->
    <script src="{{ url_for('static',filename='js/plugins/piexif.min.js') }}" type="text/javascript"></script>
    <!-- sortable.min.js is only needed if you wish to sort / rearrange files in initial preview.
        This must be loaded before fileinput.min.js -->
    <script src="{{ url_for('static',filename='js/plugins/sortable.min.js') }}" type="text/javascript"></script>
    <!-- purify.min.js is only needed if you wish to purify HTML content in your preview for HTML files.
        This must be loaded before fileinput.min.js -->
    <script src="{{ url_for('static',filename='js/plugins/purify.js') }}" type="text/javascript"></script>
    <!-- the main fileinput plugin file -->
    <script src="{{ url_for('static',filename='js/fileinput.min.js') }}"></script>
    <!-- optionally if you need a theme like font awesome theme you can include
        it as mentioned below -->
    <script src="{{ url_for('static',filename='js/themes/fa/theme.min.js') }}"></script>
    <!-- optionally if you need translation for your language then include
        locale file as mentioned below -->
    <script src="{{ url_for('static',filename='js/locales/zh.js') }}"></script>
{% endblock scripts %}
{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"
                data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">扇贝测算</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item"><a href="/export_xls">导出Excel</a></li>
                </ul>
            </div>
        </div>
    </div>
{% endblock navbar %}
<!--https://startbootstrap.com/template-overviews/4-col-portfolio/-->

app/templates/example_1.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例1 -- 自动展示缩略图</h1>
<label class="control-label">Select File</label>
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-1" name="input-1" type="file" class="file">
</form>

{% endblock %}
{% block title %}
    基本示例1 -- 自动展示缩略图
{% endblock %}

app/templates/example_2.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例2 -- 隐藏展示缩略图</h1>
<label class="control-label">Select File</label>
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-2" name="input-2" type="file" class="file"  data-show-preview="false">
</form>
{% endblock %}
{% block title %}
    基本示例2 -- 隐藏展示缩略图
{% endblock %}

app/templates/example_3.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例3 -- 利用 file input 属性控制相关选项,如本例可实现多文件上传,但不显示上传按钮</h1>
<label class="control-label">Select File</label>
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-3" name="input3[]" type="file" class="file" multiple data-show-upload="false" data-show-caption="true">
</form>
{% endblock %}
{% block title %}
    基本示例3 -- 利用 file input 属性控制相关选项,如本例可实现多文件上传,但不显示上传按钮
{% endblock %}

app/templates/example_4.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例4 -- 设置属性为只读或不可用</h1>
<label class="control-label">Select File</label>
<label class="control-label">Readonly Input</label>
<input id="input-4a" type="file" class="file" readonly="true">
<label class="control-label">Disabled Input</label>
<input id="input-4b" type="file" class="file" disabled="true">
{% endblock %}
{% block title %}
    基本示例4 -- 设置属性为只读或不可用
{% endblock %}

app/templates/example_5.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例5 -- 设置为单按钮并隐藏文件选择输入框,在上传时显示上传等待图标</h1>
<label class="control-label">Select File</label>
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-5" name="input-5[]" type="file" multiple class="file-loading">
</form>
<script>
$(document).on('ready', function() {
    $("#input-5").fileinput({showCaption: false});
});
</script>
{% endblock %}
{% block title %}
    基本示例5 -- 设置为单按钮并隐藏文件选择输入框,在上传时显示上传等待图标
{% endblock %}

app/templates/example_6.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例6 -- 设置最大上传的文件数为10</h1>
<label class="control-label">Select File</label>
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-6" name="input6[]" type="file" multiple class="file-loading">
</form>
<script>
$(document).on('ready', function() {
    $("#input-6").fileinput({
        showUpload: false,
        maxFileCount: 10,
        mainClass: "input-group-lg"
    });
});
</script>
{% endblock %}
{% block title %}
    基本示例6 -- 设置最大上传的文件数为10
{% endblock %}

app/templates/example_7.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例7 -- 设置允许上传的文件格式</h1>
<label class="control-label">Select File</label>
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-7" name="input-7[]" multiple type="file" class="file file-loading" data-allowed-file-extensions='["csv", "txt"]'>
</form>
{% endblock %}
{% block title %}
    基本示例7 -- 设置允许上传的文件格式
{% endblock %}

app/templates/example_8.html
{% extends 'basic_common/base.html' %}
{% block content %}
<h1>基本示例8 -- 使用rtl样式,让文件选择按钮居左</h1>
<span>注意:引入样式文件的时候, css/fileinput-rtl.css 必须在 the css/fileinput.css 之后引入</span>
<div dir=rtl>
    <label class="control-label">Select File</label>
</div>
<!-- note that your input must just set the `rtl` data property of the plugin or in your javascript code -->
<form method="post" role="form" enctype="multipart/form-data">
    <input id="input-8" name="input-8[]" multiple type="file" class="file-loading">
</form>
<script>
$(document).on('ready', function() {
    $("#input-8").fileinput({
        rtl: true,
        allowedFileExtensions: ["jpg", "png", "gif"]
    });
});
</script>
{% endblock %}
{% block title %}
    基本示例8 -- 使用rtl样式,让文件选择按钮居左
{% endblock %}
{% block css %}
    {{ super() }}
    <link href="{{ url_for('lib.static',filename='css/fileinput-rtl.min.css') }}" media="all" rel="stylesheet" type="text/css" />
{% endblock %}

app/templates/export_xls.html
{% extends './basic_common/mybase.html' %}
{% import './basic_common/_macros.html' as macros %}

{% block content %}
    <div class="container">
        <form method="POST" role="form" action="{{ url_for('.export_xls') }}">
            {{ form.csrf_token() }}
            {{ form.hidden_tag() }}
            {{ form.makexls }}
            <hr>
            {# 分页导航 #}
            <div class="row text-center">
                <div class="col-lg-12">
                    {{ macros.pagination_widget(pagination, '.index') }}
                </div>
            </div>
            {% for pic in pics %}
                {% if loop.first %}
                    <div class="row">
                {% endif %}
                {% if loop.index % 4 == 0 %}
                    {{ macros.make_pics2(pic, form.checked(value=pic.id)) }}
                    </div>
                    {% if not loop.last %}
                        <div class="row">
                    {% endif %}
                {% else %}
                    {{ macros.make_pics2(pic, form.checked(value=pic.id)) }}
                {% endif %}
                {% if loop.last and loop.length % 4 != 0 %}
                    </div>
                {% endif %}
            {% endfor %}
            {# 分页导航 #}
            <div class="row text-center">
                <div class="col-lg-12">
                    {{ macros.pagination_widget(pagination, '.index') }}
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

app/templates/newindex.html
{% extends 'basic_common/mybase.html' %}
{% import 'basic_common/_macros.html' as macros %}

{% block content %}
    <div class="container">
        <h4>请选择照片</h4>
        <form method="POST" role="form" action="{{ url_for('.index') }}" enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ form.hidden_tag() }}
            {{ form.pics(class='file', id='input-1') }}
        </form>
        <hr>
        <!--分页导航-->
        <div class="row text-center">
            <div class="col-lg-12">
                {{ macros.pagination_widget(pagination, '.index') }}
            </div>
        </div>

        {% for pic in pics %}
            {% if loop.first %}
                <div class="row">
            {% endif %}
            {% if loop.index % 4 == 0 %}
                {{ macros.make_pics(pic) }}
                </div>
                {% if not loop.last %}
                    <div class="row">
                {% endif %}
            {% else %}
                {{ macros.make_pics(pic) }}
            {% endif %}
            {% if loop.last and loop.length % 4 != 0 %}
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <hr>
    <!--分页导航-->
    <div class="row text-center">
        <div class="col-lg-12">
            {{ macros.pagination_widget(pagination, '.index') }}
        </div>
    </div>
{% endblock %}